### ISSUE TITLE
Channel Copy Link button doesn't work as intended

### ISSUE THREAD

**Issue by SebbyLaw** [asportnoy/canary-links#3]
~~As of commit 5188204eccb6de60f491d72ffb2a1453849cc5df the features added in #1 no longer work.~~

Edit: #1 never worked

**Comment by asportnoy** [comment]
Any errors in the console? There's no reason those changes should've caused anything

**Comment by SebbyLaw** [comment]
No errors in console. Seems like this issue was my implementation of #1. I didn't realize the "Copy Link" `MenuItem` for the channel context menus had a different key and didn't test it.

I've written a fix for text and voice channels in #4 but I can't seem to figure out how to make the `ChannelListThreadContextMenu` context menu work.
